// Elenco marche/modelli più comuni sui mercati coperti dall'app (Europa,
// Nord America, India, Sud-est asiatico, Russia, Cina). Non è (e non può
// essere) esaustivo: chi non trova la propria marca o modello può sempre
// scegliere "Altra marca..." / "Altro modello..." e scrivere a mano.

export interface CarBrand {
  brand: string;
  models: string[];
}

export const CAR_CATALOG: CarBrand[] = [
  { brand: "Abarth", models: ["500", "595", "695"] },
  { brand: "Acura", models: ["ILX", "TLX", "RDX", "MDX"] },
  { brand: "Aiways", models: ["U5", "U6"] },
  { brand: "Alfa Romeo", models: ["Giulietta", "Giulia", "Stelvio", "MiTo", "Tonale"] },
  { brand: "Aston Martin", models: ["Vantage", "DB11", "DBX"] },
  { brand: "Audi", models: ["A1", "A3", "A4", "A5", "A6", "Q2", "Q3", "Q5", "Q7", "e-tron"] },
  { brand: "Avatr", models: ["11", "12"] },
  { brand: "BAIC", models: ["X55", "Beijing X7"] },
  { brand: "Baojun", models: ["530", "510", "Yep"] },
  { brand: "Belgee", models: ["X50", "X70"] },
  { brand: "Bentley", models: ["Continental", "Bentayga", "Flying Spur"] },
  { brand: "BMW", models: ["Serie 1", "Serie 2", "Serie 3", "Serie 5", "X1", "X2", "X3", "X5", "i3", "i4"] },
  { brand: "Bugatti", models: ["Chiron", "Veyron"] },
  { brand: "Buick", models: ["Encore", "Enclave", "Envision"] },
  { brand: "BYD", models: ["Atto 3", "Dolphin", "Seal", "Han", "Song Plus", "Tang"] },
  { brand: "Cadillac", models: ["Escalade", "XT5", "CT5"] },
  { brand: "Changan", models: ["CS35", "CS55", "Eado", "UNI-T"] },
  { brand: "Chery", models: ["Tiggo 4", "Tiggo 7", "Tiggo 8", "Omoda 5"] },
  { brand: "Chevrolet", models: ["Spark", "Onix", "Cruze", "Equinox", "Tahoe", "Silverado", "Camaro"] },
  { brand: "Chrysler", models: ["300", "Pacifica"] },
  { brand: "Citroën", models: ["C1", "C3", "C3 Aircross", "C4", "C4 Cactus", "C5 Aircross", "Berlingo"] },
  { brand: "Cupra", models: ["Formentor", "Leon", "Born", "Ateca"] },
  { brand: "Dacia", models: ["Sandero", "Duster", "Jogger", "Spring"] },
  { brand: "Daewoo", models: ["Matiz", "Nubira", "Lanos"] },
  { brand: "Daihatsu", models: ["Xenia", "Ayla", "Terios", "Sigra", "Rocky"] },
  { brand: "Datsun", models: ["Go", "Go+", "Redi-GO"] },
  { brand: "Deepal", models: ["S07", "SL03"] },
  { brand: "Denza", models: ["D9", "N7"] },
  { brand: "Dongfeng", models: ["AX7", "Box", "Nammi"] },
  { brand: "DS Automobiles", models: ["DS3", "DS4", "DS7"] },
  { brand: "Euler / Ora", models: ["Good Cat", "Funky Cat"] },
  { brand: "Exeed", models: ["TXL", "LX"] },
  { brand: "FAW", models: ["Bestune T77", "Hongqi"] },
  { brand: "Ferrari", models: ["488", "Roma", "Portofino"] },
  { brand: "Fiat", models: ["Panda", "500", "500L", "500X", "Tipo", "Punto", "Ducato", "Doblò"] },
  { brand: "Ford", models: ["Fiesta", "Focus", "Puma", "Kuga", "Ecosport", "F-150", "Ranger", "Mustang Mach-E"] },
  { brand: "GAC", models: ["Emkoo", "Aion Y", "GS3"] },
  { brand: "Geely", models: ["Coolray", "Emgrand", "Tugella"] },
  { brand: "Genesis", models: ["G70", "G80", "GV70", "GV80"] },
  { brand: "GMC", models: ["Sierra", "Terrain", "Yukon"] },
  { brand: "Great Wall / Haval", models: ["H6", "Jolion", "H9"] },
  { brand: "Holden", models: ["Commodore", "Astra", "Colorado"] },
  { brand: "Honda", models: ["Civic", "Jazz", "HR-V", "CR-V", "City", "Brio"] },
  { brand: "Hongqi", models: ["H5", "HS5", "E-HS9"] },
  { brand: "Hummer", models: ["H2", "H3", "EV"] },
  { brand: "Hyundai", models: ["i10", "i20", "i30", "Kona", "Tucson", "Santa Fe", "Ioniq", "Creta", "Venue"] },
  { brand: "Infiniti", models: ["Q50", "QX50", "QX60"] },
  { brand: "Isuzu", models: ["D-Max", "MU-X"] },
  { brand: "JAC", models: ["JS4", "e-JS4", "T6"] },
  { brand: "Jaecoo", models: ["J7", "J8"] },
  { brand: "Jaguar", models: ["XE", "XF", "F-Pace", "E-Pace"] },
  { brand: "Jeep", models: ["Renegade", "Compass", "Wrangler", "Avenger"] },
  { brand: "Jetour", models: ["Dashing", "X70"] },
  { brand: "Kaiyi", models: ["X3", "X7"] },
  { brand: "Kia", models: ["Picanto", "Rio", "Ceed", "Sportage", "Niro", "Seltos", "EV6"] },
  { brand: "KGM (SsangYong)", models: ["Torres", "Rexton", "Tivoli"] },
  { brand: "Lada", models: ["Vesta", "Granta", "Niva", "XRAY"] },
  { brand: "Lamborghini", models: ["Huracán", "Urus"] },
  { brand: "Lancia", models: ["Ypsilon"] },
  { brand: "Land Rover", models: ["Defender", "Discovery", "Range Rover", "Range Rover Evoque", "Range Rover Sport"] },
  { brand: "LDV / Maxus", models: ["T60", "D90", "eDeliver 3"] },
  { brand: "Leapmotor", models: ["T03", "C10"] },
  { brand: "Lexus", models: ["CT", "IS", "ES", "NX", "RX", "UX"] },
  { brand: "Li Auto", models: ["L7", "L8", "L9"] },
  { brand: "Lincoln", models: ["Corsair", "Aviator", "Navigator"] },
  { brand: "Livan", models: ["S6", "8"] },
  { brand: "Lynk & Co", models: ["01", "02", "03"] },
  { brand: "Mahindra", models: ["Scorpio", "XUV700", "Thar", "Bolero"] },
  { brand: "Maruti Suzuki", models: ["Swift", "Baleno", "WagonR", "Ertiga", "Brezza"] },
  { brand: "Maserati", models: ["Ghibli", "Levante", "Grecale"] },
  { brand: "Mazda", models: ["Mazda2", "Mazda3", "CX-3", "CX-5", "MX-5"] },
  { brand: "McLaren", models: ["570S", "720S", "Artura"] },
  { brand: "Mercedes-Benz", models: ["Classe A", "Classe B", "Classe C", "CLA", "GLA", "GLC"] },
  { brand: "MG", models: ["MG3", "MG4", "ZS", "HS"] },
  { brand: "Mini", models: ["Cooper", "Countryman", "Clubman"] },
  { brand: "Mitsubishi", models: ["Space Star", "ASX", "Eclipse Cross", "Outlander", "Xpander", "Pajero"] },
  { brand: "Nio", models: ["ET5", "ET7", "EL6"] },
  { brand: "Nissan", models: ["Micra", "Juke", "Qashqai", "X-Trail", "Leaf", "Navara"] },
  { brand: "Opel", models: ["Corsa", "Astra", "Crossland", "Grandland", "Mokka"] },
  { brand: "Peugeot", models: ["108", "208", "308", "2008", "3008", "5008", "Partner"] },
  { brand: "Porsche", models: ["911", "Cayenne", "Macan", "Panamera", "Taycan"] },
  { brand: "Ram", models: ["1500", "2500"] },
  { brand: "Renault", models: ["Clio", "Captur", "Megane", "Kadjar", "Scenic", "Zoe", "Twingo", "Kwid"] },
  { brand: "Seat", models: ["Ibiza", "Leon", "Arona", "Ateca"] },
  { brand: "Škoda", models: ["Fabia", "Octavia", "Kamiq", "Karoq", "Kodiaq"] },
  { brand: "Smart", models: ["Fortwo", "Forfour"] },
  { brand: "Subaru", models: ["Impreza", "XV", "Forester", "Outback"] },
  { brand: "Suzuki", models: ["Swift", "Vitara", "S-Cross", "Ignis"] },
  { brand: "Tata", models: ["Tiago", "Nexon", "Punch", "Harrier"] },
  { brand: "Tesla", models: ["Model 3", "Model Y", "Model S", "Model X"] },
  { brand: "Toyota", models: ["Aygo", "Yaris", "Corolla", "C-HR", "RAV4", "Prius", "Innova", "Avanza", "Hilux"] },
  { brand: "Volkswagen", models: ["Polo", "Golf", "Passat", "T-Roc", "Tiguan", "ID.3", "ID.4", "Up!"] },
  { brand: "Volvo", models: ["XC40", "XC60", "XC90", "V60", "S60"] },
  { brand: "XPeng", models: ["P7", "G6", "G9"] },
  { brand: "Zeekr", models: ["001", "007", "009"] },
];

export const OTHER_BRAND = "__altra_marca__";
export const OTHER_MODEL = "__altro_modello__";
