// Descrizioni dei codici DTC generici OBD-II (P0xxx) più comuni.
// Sono "generici": validi per qualunque costruttore. I codici P1xxx/P2xxx/P3xxx
// specifici del produttore non sono coperti da questo dizionario.

export const DTC_DESCRIPTIONS: Record<string, string> = {
  P0100: "Circuito portata aria (MAF) - malfunzionamento",
  P0101: "Circuito portata aria (MAF) - range/prestazioni",
  P0110: "Circuito temperatura aria aspirata - malfunzionamento",
  P0115: "Circuito temperatura liquido raffreddamento - malfunzionamento",
  P0116: "Circuito temperatura liquido raffreddamento - range/prestazioni",
  P0120: "Circuito posizione farfalla/pedale (A) - malfunzionamento",
  P0125: "Temperatura liquido insufficiente per closed loop carburazione",
  P0128: "Termostato - temperatura sotto la soglia regolazione",
  P0130: "Sonda lambda banco1 sensore1 - circuito malfunzionante",
  P0133: "Sonda lambda banco1 sensore1 - risposta lenta",
  P0135: "Sonda lambda banco1 sensore1 - riscaldatore malfunzionante",
  P0136: "Sonda lambda banco1 sensore2 - circuito malfunzionante",
  P0141: "Sonda lambda banco1 sensore2 - riscaldatore malfunzionante",
  P0170: "Fuel trim banco1 - malfunzionamento",
  P0171: "Fuel trim banco1 - miscela povera",
  P0172: "Fuel trim banco1 - miscela ricca",
  P0174: "Fuel trim banco2 - miscela povera",
  P0175: "Fuel trim banco2 - miscela ricca",
  P0200: "Circuito iniettori - malfunzionamento",
  P0201: "Circuito iniettore cilindro 1 - malfunzionamento",
  P0217: "Motore surriscaldato",
  P0230: "Circuito primario pompa carburante - malfunzionamento",
  P0300: "Accensioni mancate rilevate su più cilindri (random misfire)",
  P0301: "Accensione mancata cilindro 1",
  P0302: "Accensione mancata cilindro 2",
  P0303: "Accensione mancata cilindro 3",
  P0304: "Accensione mancata cilindro 4",
  P0325: "Circuito sensore battito (knock) - malfunzionamento",
  P0335: "Circuito sensore posizione albero motore (CKP) - malfunzionamento",
  P0340: "Circuito sensore posizione albero a camme (CMP) - malfunzionamento",
  P0400: "Flusso ricircolo gas di scarico (EGR) - malfunzionamento",
  P0401: "Flusso EGR insufficiente",
  P0402: "Flusso EGR eccessivo",
  P0420: "Efficienza catalizzatore banco1 sotto soglia",
  P0430: "Efficienza catalizzatore banco2 sotto soglia",
  P0440: "Sistema controllo emissioni evaporative (EVAP) - malfunzionamento",
  P0441: "EVAP - flusso di sfiato incorretto",
  P0442: "EVAP - perdita rilevata (media)",
  P0446: "EVAP - circuito valvola sfiato canister bloccato",
  P0455: "EVAP - perdita rilevata (grande, es. tappo serbatoio)",
  P0456: "EVAP - perdita rilevata (piccola)",
  P0500: "Circuito sensore velocità veicolo (VSS) - malfunzionamento",
  P0505: "Circuito controllo minimo (idle) - malfunzionamento",
  P0506: "Regime minimo inferiore all'atteso",
  P0507: "Regime minimo superiore all'atteso",
  P0562: "Tensione di sistema bassa",
  P0563: "Tensione di sistema alta",
  P0600: "Malfunzionamento link seriale centralina",
  P0601: "Errore memoria/checksum centralina motore",
  P0605: "Errore memoria ROM centralina motore",
  P0700: "Malfunzionamento sistema controllo cambio (richiede scansione cambio)",
  P0715: "Circuito sensore velocità ingresso/turbina cambio",
  P0720: "Circuito sensore velocità uscita cambio",
};

/** Ritorna una descrizione in italiano per un codice DTC, se presente nel dizionario generico. */
export function describeDtc(code: string): string | null {
  return DTC_DESCRIPTIONS[code.toUpperCase()] ?? null;
}
