// Descrizioni dei codici DTC generici OBD-II (P0xxx) più comuni, basate sullo
// standard SAE J2012 / ISO 15031-6 (definizione pubblica di settore, non
// proprietaria di nessun singolo produttore o rivenditore). Sono "generici":
// validi per qualunque costruttore. I codici P1xxx/P2xxx/P3xxx specifici del
// produttore non sono coperti da questo dizionario.
//
// Nota: a differenza del resto dell'app, queste descrizioni sono solo in
// italiano — tradurle in tutte le lingue supportate è un lavoro a parte,
// non ancora fatto.

export const DTC_DESCRIPTIONS: Record<string, string> = {
  // ---------- Sistema alimentazione aria/carburante ----------
  P0100: "Circuito portata aria (MAF) - malfunzionamento",
  P0101: "Circuito portata aria (MAF) - range/prestazioni",
  P0102: "Circuito portata aria (MAF) - segnale basso",
  P0103: "Circuito portata aria (MAF) - segnale alto",
  P0104: "Circuito portata aria (MAF) - segnale intermittente",
  P0105: "Circuito pressione collettore (MAP) - malfunzionamento",
  P0106: "Circuito pressione collettore (MAP) - range/prestazioni",
  P0107: "Circuito pressione collettore (MAP) - segnale basso",
  P0108: "Circuito pressione collettore (MAP) - segnale alto",
  P0109: "Circuito pressione collettore (MAP) - segnale intermittente",
  P0110: "Circuito temperatura aria aspirata - malfunzionamento",
  P0111: "Circuito temperatura aria aspirata - range/prestazioni",
  P0112: "Circuito temperatura aria aspirata - segnale basso",
  P0113: "Circuito temperatura aria aspirata - segnale alto",
  P0115: "Circuito temperatura liquido raffreddamento - malfunzionamento",
  P0116: "Circuito temperatura liquido raffreddamento - range/prestazioni",
  P0117: "Circuito temperatura liquido raffreddamento - segnale basso",
  P0118: "Circuito temperatura liquido raffreddamento - segnale alto",
  P0120: "Circuito posizione farfalla/pedale (A) - malfunzionamento",
  P0121: "Circuito posizione farfalla/pedale (A) - range/prestazioni",
  P0122: "Circuito posizione farfalla/pedale (A) - segnale basso",
  P0123: "Circuito posizione farfalla/pedale (A) - segnale alto",
  P0125: "Temperatura liquido insufficiente per closed loop carburazione",
  P0128: "Termostato - temperatura sotto la soglia regolazione",
  P0130: "Sonda lambda banco1 sensore1 - circuito malfunzionante",
  P0131: "Sonda lambda banco1 sensore1 - segnale basso",
  P0132: "Sonda lambda banco1 sensore1 - segnale alto",
  P0133: "Sonda lambda banco1 sensore1 - risposta lenta",
  P0134: "Sonda lambda banco1 sensore1 - nessuna attività rilevata",
  P0135: "Sonda lambda banco1 sensore1 - riscaldatore malfunzionante",
  P0136: "Sonda lambda banco1 sensore2 - circuito malfunzionante",
  P0137: "Sonda lambda banco1 sensore2 - segnale basso",
  P0138: "Sonda lambda banco1 sensore2 - segnale alto",
  P0139: "Sonda lambda banco1 sensore2 - risposta lenta",
  P0140: "Sonda lambda banco1 sensore2 - nessuna attività rilevata",
  P0141: "Sonda lambda banco1 sensore2 - riscaldatore malfunzionante",
  P0150: "Sonda lambda banco2 sensore1 - circuito malfunzionante",
  P0151: "Sonda lambda banco2 sensore1 - segnale basso",
  P0152: "Sonda lambda banco2 sensore1 - segnale alto",
  P0153: "Sonda lambda banco2 sensore1 - risposta lenta",
  P0155: "Sonda lambda banco2 sensore1 - riscaldatore malfunzionante",
  P0156: "Sonda lambda banco2 sensore2 - circuito malfunzionante",
  P0157: "Sonda lambda banco2 sensore2 - segnale basso",
  P0158: "Sonda lambda banco2 sensore2 - segnale alto",
  P0161: "Sonda lambda banco2 sensore2 - riscaldatore malfunzionante",
  P0170: "Fuel trim banco1 - malfunzionamento",
  P0171: "Fuel trim banco1 - miscela povera",
  P0172: "Fuel trim banco1 - miscela ricca",
  P0173: "Fuel trim banco2 - malfunzionamento",
  P0174: "Fuel trim banco2 - miscela povera",
  P0175: "Fuel trim banco2 - miscela ricca",
  P0180: "Circuito sensore temperatura carburante A - malfunzionamento",
  P0182: "Circuito sensore temperatura carburante A - segnale basso",
  P0183: "Circuito sensore temperatura carburante A - segnale alto",
  P0190: "Circuito sensore pressione rail carburante - malfunzionamento",
  P0191: "Circuito sensore pressione rail carburante - range/prestazioni",

  // ---------- Iniettori e pompa carburante ----------
  P0200: "Circuito iniettori - malfunzionamento",
  P0201: "Circuito iniettore cilindro 1 - malfunzionamento",
  P0202: "Circuito iniettore cilindro 2 - malfunzionamento",
  P0203: "Circuito iniettore cilindro 3 - malfunzionamento",
  P0204: "Circuito iniettore cilindro 4 - malfunzionamento",
  P0205: "Circuito iniettore cilindro 5 - malfunzionamento",
  P0206: "Circuito iniettore cilindro 6 - malfunzionamento",
  P0217: "Motore surriscaldato",
  P0219: "Regime motore eccessivo (overspeed)",
  P0230: "Circuito primario pompa carburante - malfunzionamento",
  P0231: "Circuito secondario pompa carburante - segnale basso",
  P0232: "Circuito secondario pompa carburante - segnale alto",

  // ---------- Accensione e sensori albero motore/camme ----------
  P0300: "Accensioni mancate rilevate su più cilindri (random misfire)",
  P0301: "Accensione mancata cilindro 1",
  P0302: "Accensione mancata cilindro 2",
  P0303: "Accensione mancata cilindro 3",
  P0304: "Accensione mancata cilindro 4",
  P0305: "Accensione mancata cilindro 5",
  P0306: "Accensione mancata cilindro 6",
  P0325: "Circuito sensore battito (knock) - malfunzionamento",
  P0326: "Circuito sensore battito - range/prestazioni",
  P0327: "Circuito sensore battito - segnale basso",
  P0328: "Circuito sensore battito - segnale alto",
  P0335: "Circuito sensore posizione albero motore (CKP) - malfunzionamento",
  P0336: "Circuito sensore posizione albero motore (CKP) - range/prestazioni",
  P0337: "Circuito sensore posizione albero motore (CKP) - segnale basso",
  P0338: "Circuito sensore posizione albero motore (CKP) - segnale alto",
  P0340: "Circuito sensore posizione albero a camme (CMP) - malfunzionamento",
  P0341: "Circuito sensore posizione albero a camme (CMP) - range/prestazioni",
  P0342: "Circuito sensore posizione albero a camme (CMP) - segnale basso",
  P0343: "Circuito sensore posizione albero a camme (CMP) - segnale alto",
  P0350: "Circuito primario/secondario bobina accensione - malfunzionamento",
  P0351: "Circuito bobina accensione A - malfunzionamento",
  P0352: "Circuito bobina accensione B - malfunzionamento",
  P0353: "Circuito bobina accensione C - malfunzionamento",
  P0354: "Circuito bobina accensione D - malfunzionamento",

  // ---------- EGR e sistema emissioni ----------
  P0400: "Flusso ricircolo gas di scarico (EGR) - malfunzionamento",
  P0401: "Flusso EGR insufficiente",
  P0402: "Flusso EGR eccessivo",
  P0403: "Circuito controllo valvola EGR - malfunzionamento",
  P0404: "Circuito controllo valvola EGR - range/prestazioni",
  P0405: "Circuito sensore posizione valvola EGR A - segnale basso",
  P0406: "Circuito sensore posizione valvola EGR A - segnale alto",
  P0410: "Sistema iniezione aria secondaria - malfunzionamento",
  P0411: "Sistema iniezione aria secondaria - flusso scorretto",
  P0420: "Efficienza catalizzatore banco1 sotto soglia",
  P0421: "Efficienza catalizzatore banco1 (warm up) sotto soglia",
  P0430: "Efficienza catalizzatore banco2 sotto soglia",
  P0431: "Efficienza catalizzatore banco2 (warm up) sotto soglia",
  P0440: "Sistema controllo emissioni evaporative (EVAP) - malfunzionamento",
  P0441: "EVAP - flusso di sfiato incorretto",
  P0442: "EVAP - perdita rilevata (media)",
  P0443: "EVAP - circuito valvola purge - malfunzionamento",
  P0446: "EVAP - circuito valvola sfiato canister bloccato",
  P0449: "EVAP - circuito elettrovalvola sfiato canister - malfunzionamento",
  P0450: "EVAP - circuito sensore pressione serbatoio - malfunzionamento",
  P0455: "EVAP - perdita rilevata (grande, es. tappo serbatoio)",
  P0456: "EVAP - perdita rilevata (piccola)",
  P0457: "EVAP - perdita rilevata o tappo serbatoio allentato/mancante",

  // ---------- Sensori velocità veicolo, minimo, tensione ----------
  P0500: "Circuito sensore velocità veicolo (VSS) - malfunzionamento",
  P0501: "Circuito sensore velocità veicolo - range/prestazioni",
  P0503: "Circuito sensore velocità veicolo - segnale intermittente/rumoroso",
  P0505: "Circuito controllo minimo (idle) - malfunzionamento",
  P0506: "Regime minimo inferiore all'atteso",
  P0507: "Regime minimo superiore all'atteso",
  P0510: "Circuito interruttore posizione farfalla chiusa - malfunzionamento",
  P0520: "Circuito sensore pressione olio motore - malfunzionamento",
  P0530: "Circuito sensore pressione refrigerante A/C - malfunzionamento",
  P0560: "Tensione di sistema - malfunzionamento",
  P0562: "Tensione di sistema bassa",
  P0563: "Tensione di sistema alta",

  // ---------- Centralina motore ----------
  P0600: "Malfunzionamento link seriale centralina",
  P0601: "Errore memoria/checksum centralina motore",
  P0602: "Programmazione centralina motore non completata",
  P0603: "Errore memoria KAM (Keep Alive Memory) centralina",
  P0604: "Errore memoria RAM centralina motore",
  P0605: "Errore memoria ROM centralina motore",
  P0606: "Malfunzionamento processore interno centralina",
  P0620: "Circuito controllo alternatore/regolatore - malfunzionamento",
  P0621: "Circuito spia carica generatore - malfunzionamento",
  P0622: "Circuito controllo campo generatore - malfunzionamento",
  P0630: "VIN non programmato nella centralina motore",
  P0633: "Chiave/immobilizer non programmato nella centralina motore",
  P0650: "Circuito spia malfunzionamento (MIL) - malfunzionamento",

  // ---------- Cambio automatico ----------
  P0700: "Malfunzionamento sistema controllo cambio (richiede scansione cambio)",
  P0701: "Range/prestazioni sistema controllo cambio",
  P0702: "Circuito elettrico sistema controllo cambio",
  P0703: "Circuito interruttore pedale freno/stop - malfunzionamento",
  P0705: "Circuito sensore posizione selettore marce (PRNDL) - malfunzionamento",
  P0710: "Circuito sensore temperatura fluido cambio - malfunzionamento",
  P0711: "Circuito sensore temperatura fluido cambio - range/prestazioni",
  P0715: "Circuito sensore velocità ingresso/turbina cambio - malfunzionamento",
  P0716: "Circuito sensore velocità ingresso/turbina - range/prestazioni",
  P0720: "Circuito sensore velocità uscita cambio - malfunzionamento",
  P0721: "Circuito sensore velocità uscita - range/prestazioni",
  P0725: "Circuito sensore velocità motore - malfunzionamento",
  P0730: "Rapporto marcia scorretto",
  P0731: "Rapporto errato in 1ª marcia",
  P0732: "Rapporto errato in 2ª marcia",
  P0733: "Rapporto errato in 3ª marcia",
  P0734: "Rapporto errato in 4ª marcia",
  P0740: "Circuito frizione convertitore di coppia - malfunzionamento",
  P0741: "Frizione convertitore di coppia - bloccata/slittamento",
  P0743: "Circuito frizione convertitore di coppia - elettrico",
  P0750: "Circuito elettrovalvola A cambio - malfunzionamento",
  P0755: "Circuito elettrovalvola B cambio - malfunzionamento",
  P0760: "Circuito elettrovalvola C cambio - malfunzionamento",

  // ---------- Fluidi cambio / retromarcia ----------
  P0830: "Circuito interruttore frizione (cambio manuale) - malfunzionamento",
  P0837: "Circuito interruttore retromarcia - malfunzionamento",
  P0841: "Circuito sensore pressione fluido cambio A - malfunzionamento",
};

/** Ritorna una descrizione in italiano per un codice DTC, se presente nel dizionario generico. */
export function describeDtc(code: string): string | null {
  return DTC_DESCRIPTIONS[code.toUpperCase()] ?? null;
}
